config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get '/mypage', to: 'mypage#show'
  get 'users/index'
  get 'users/show'
  devise_for :users
  root to: 'articles#index'
  # resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user

  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :users, through: :article_tags
  has_many :article_tags, dependent: :destroy
  has_one :mypage

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_article, only: %i[edit update destroy]

  # GET /articles
  def index
    if params[:title].present?
      @articles = Article.where('title LIKE ?', "%#{params[:title]}%").page(params[:page])
    else
      @articles = Article.all.page(params[:page])
    end
  end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
    @user = @article.user
  end

  # GET /articles/new
  def new
    @article =Article.new
  end

  # POST /articles
  def create
    @article = current_user.articles.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.user != current_user
      redirect_to articles_path
    else
      if @article.update(article_params)
        redirect_to articles_path
      else
        render :edit
      end
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :user_id, tag_ids: [])
    end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  def show
    if params[:title].present?
      @articles = current_user.articles.where('title LIKE ?', "%#{params[:title]}%").page(params[:page])
    else
      @articles = current_user.articles.page(params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count%> 件の対応が必要です</h2></h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <div class="mb-3">
    <%= form.label :title, "タイトル", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, "内容", class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>

<table class="table">
  <%= render partial: "search" %>
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <span>Eメール：</span><%= @user.email %>
</p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
    <% @article.tags.each do |tag| %>
      <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
    <% end %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'TOP', articles_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'マイページ', mypage_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'サインアップ', new_user_registration_path, class: "nav-link active"%>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link active" %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
      <%= render partial: "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
 </html>

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/show.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ</h1>
<%= render partial: "search" %>
<%= paginate @articles %>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
          <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>